### ISSUE TITLE
Player does not jump repeatedly if Z is held down after moving sideways

### ISSUE THREAD

**Issue by justinsunyt** [Harvard-Westlake/Math-Attack#150]
- [x] Track keydown for jump button
- [x] Create while loop in jump function to jump repeatedly until stopped

**Comment by MicahGold** [comment]
Hey Justin, you didn't leave a space to review which is cringe (I did it myself the first time around -- I get it, but MICHAEL AND I BOTH REVIEWED IT AND IT WORKS!!!! SO MR. THEISS CONSIDER IT APPROVED AFTER THE FACT)
